### ISSUE TITLE
Throws decoding tuple containing null

### ISSUE THREAD

**Issue by zwilias** [tsloughter/pg_types#4]
When a tuple contains `null`'s things appear to explode:

```
pgo:query("SELECT (NULL, NULL)").
** exception error: no function clause matching pg_record:decode_tuple_no_oids(<<0,0,2,193,255,255,255,255,0,0,2,193,255,255,255,255>>,
                                                                               2,default,[],[]) (/[...]/_build/default/lib/pg_types/src/pg_record.erl, line 61)
```

There's some code that appears to try to handle this, but it doesn't really seem to like the "extra" bytes that are in front of the actual `-1` values...
https://github.com/tsloughter/pg_types/blob/17b16db10e7474280b5114d798107a795677ff69/src/pg_record.erl#L63-L66

For what it's worth, OID `<<0, 0, 2, 193>>` (705) corresponds to `unknown`, in my `pg_types` table.

**Comment by tsloughter** [comment]
Thanks, I'll take a look at this.

**Comment by tsloughter** [comment]
Hey, finally remembered to fix this. It is fixed in master.
